### ISSUE TITLE
MongoDBRef encoding?

### ISSUE THREAD

**Issue by snowbabyjia** [mcuadros/bson-hni#3]
Is it missing or implicitly taken care of by the array encoding? Thanks

**Comment by mcuadros** [comment]
Looks like mongoDbRef support is missing :/

I will work on it asap. Keep an eye at https://github.com/mongofill/mongofill-hhvm

**Comment by snowbabyjia** [comment]
Thanks for the pointers!

**Comment by jmikola** [comment]
MongoDBRef isn't a value object, so there's nothing to encode here. The existing code path for converting associative arrays into BSON objects is sufficient. The PHP class is just a bunch of static methods to create [DBRef objects](http://docs.mongodb.org/manual/reference/database-references/#dbrefs) and conveniently fetch them.

That said, when inserting documents, `$` should not be allowed to prefix fields unless we're dealing with a DBRef (see: [PHP-958](https://jira.mongodb.org/browse/PHP-958)). Obviously, this isn't a blanket rule for BSON serialization, since we should allow `$` for update and query objects. This would require some cooperation between bson-hni and mongofill to selectively enforce the rule.

**Comment by mcuadros** [comment]
Reviewing the code, yes the encoding of non-suported objects is done via internal object methods toArray, recovering all the public values. So MongoDBRef is supported.

About `$` at  the name fields, maybe this is a competence for libbson? To avoid duplicate code. Or just verify if the array values match the DBRef pattern and if not throw a exception. 

This is implemented in the PHP version?

**Comment by jmikola** [comment]
It's not yet implemented in the PHP driver. We just have a ticket for it.

That `$` restriction logic probably belongs in a driver instead of a BSON library, since it's very dependent on the case of the serialization. If it is a function of the BSON encoder, it would need to be controlled via some flag/option.
